### ISSUE TITLE
Va a continuar con este proyecto?

### ISSUE THREAD

**Issue by WodsonKun** [bm0x/Super-Mario-Run-UWP#1]
Se es asi, puedo ayudar con algunos assets para el juego... Usted quiere (o querido) para hacer el juego en 2D, 2.5D y 3D?
Se no es asi... ¡Qué lástima, no?

**Comment by WodsonKun** [comment]
En 2D, podrias utilizar algunos sprites más modernos.
En 2.5D, sprites de New Super Mario Bros. DS.
En 3D, lo mismo de 2.5D, mas en una cualidad mejor...

**Comment by bm0x** [comment]
hola, pues, no, no pienso continuar con este proyecto, ya que usar solo html... (ya que C++ y C# no lo manejo muy bien) me complica bastante...

**Comment by bm0x** [comment]
en un momento, pensaba que hacerlo en HTML me serviría bastante
pero realmente me equivoqué...

**Comment by WodsonKun** [comment]
Entiende portugués? Yo soy Brasilero... E no me gustas mucho hablar o escribir en español...

**Comment by bm0x** [comment]
nothing my friend, Spanish is my Native Language and... i don´t know much english....

**Comment by WodsonKun** [comment]
Ok, voy tentar hablar en español...

**Comment by bm0x** [comment]
Está bien amigo, como ya dije, yo ya no quise continuar con el proyecto, porque HTML se me complica cuando es desarrollo móvil, y más si es el ámbito gaming...

**Comment by WodsonKun** [comment]
Porqué no tentas hacelo en Gamemaker: Studio? És muy fácil de hacer juegos en Gamemaker. E es compatible con Windows Phone 8! Tu juego puede ser publicado en Windows Store e ser jugado en Windows Phone 8, 8.1 y Windows 10 Mobile!

**Comment by bm0x** [comment]
Intenté hacerlo, pero la idea que tenía no era válida como para plasmarla en el juego, porque a muchos no les gustaría, o quizá cosas peores...

**Comment by bm0x** [comment]
Quizá en unos días más intente volver a trabajar con Super Mario Run UWP
Pero ahora creo que tendría las cosas más claras

**Comment by bm0x** [comment]
Y obvio... Tratar de ofrecer todos los mundos completamente gratuitos....

**Comment by WodsonKun** [comment]
... Ok...

**Comment by WodsonKun** [comment]
Pero, seria una gran aplicación...

**Comment by bm0x** [comment]
Ahora mismo, estoy en otros proyectos, estoy muy ocupado además de los asuntos escolares que me mantienen ocupado el día a día, pero aún así intentaré llevar ideas nuevas, y si quieres ayudarme, pues, bienvenido! :D

**Comment by WodsonKun** [comment]
Yo voy a cerrar esta issue.

**Comment by WodsonKun** [comment]
OK, intentare hacer una Tech Demo de Super Mario Run... Cuando finalizarlo, lo contactares!

**Comment by bm0x** [comment]
Está bien, si quieres otro día intentamos hablar ;)
